// flow-typed signature: 1bd3b0ee6c8a9291452375adc4980573
// flow-typed version: <<STUB>>/react-spinner_v^0.2.7/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spinner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spinner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spinner/build/index' {
  declare module.exports: any;
}

declare module 'react-spinner/server' {
  declare module.exports: any;
}

declare module 'react-spinner/webpack.config' {
  declare module.exports: any;
}

declare module 'react-spinner/webpack.prod.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spinner/build/index.js' {
  declare module.exports: $Exports<'react-spinner/build/index'>;
}
declare module 'react-spinner/index' {
  declare module.exports: $Exports<'react-spinner'>;
}
declare module 'react-spinner/index.jsx' {
  declare module.exports: $Exports<'react-spinner'>;
}
declare module 'react-spinner/server.js' {
  declare module.exports: $Exports<'react-spinner/server'>;
}
declare module 'react-spinner/webpack.config.js' {
  declare module.exports: $Exports<'react-spinner/webpack.config'>;
}
declare module 'react-spinner/webpack.prod.config.js' {
  declare module.exports: $Exports<'react-spinner/webpack.prod.config'>;
}
